<?php
/**
 * @author ueaner <ueaner@gmail.com>
 */
// classmap
return [
    'Soli\\Application'                  => __DIR__ . '/Application.php',
    'Soli\\BaseDispatcher'               => __DIR__ . '/BaseDispatcher.php',
    'Soli\\Collection'                   => __DIR__ . '/Collection.php',
    'Soli\\Controller'                   => __DIR__ . '/Controller.php',
    'Soli\\Component'                    => __DIR__ . '/Component.php',
    'Soli\\Cli\\Application'             => __DIR__ . '/Cli/Application.php',
    'Soli\\Cli\\Dispatcher'              => __DIR__ . '/Cli/Dispatcher.php',
    'Soli\\Cli\\Task'                    => __DIR__ . '/Cli/Task.php',
    'Soli\\Db'                           => __DIR__ . '/Db.php',
    'Soli\\Di\\Container'                => __DIR__ . '/Di/Container.php',
    'Soli\\Di\\Injectable'               => __DIR__ . '/Di/Injectable.php',
    'Soli\\Di\\InjectionAwareInterface'  => __DIR__ . '/Di/InjectionAwareInterface.php',
    'Soli\\Di\\Service'                  => __DIR__ . '/Di/Service.php',
    'Soli\\Dispatcher'                   => __DIR__ . '/Dispatcher.php',
    'Soli\\Exception'                    => __DIR__ . '/Exception.php',
    'Soli\\Events\\Event'                => __DIR__ . '/Events/Event.php',
    'Soli\\Events\\EventsAwareInterface' => __DIR__ . '/Events/EventsAwareInterface.php',
    'Soli\\Events\\Manager'              => __DIR__ . '/Events/Manager.php',
    'Soli\\Events\\ManagerInterface'     => __DIR__ . '/Events/ManagerInterface.php',
    'Soli\\Filter'                       => __DIR__ . '/Filter.php',
    'Soli\\Http\\Request'                => __DIR__ . '/Http/Request.php',
    'Soli\\Http\\Response'               => __DIR__ . '/Http/Response.php',
    'Soli\\Loader'                       => __DIR__ . '/Loader.php',
    'Soli\\Logger'                       => __DIR__ . '/Logger.php',
    'Psr\\Log\\LoggerInterface'          => __DIR__ . '/LoggerInterface.php',
    'Soli\\Model'                        => __DIR__ . '/Model.php',
    'Soli\\ModelExtra'                   => __DIR__ . '/ModelExtra.php',
    'Soli\\Session'                      => __DIR__ . '/Session.php',
    'Soli\\Session\\Flash'               => __DIR__ . '/Session/Flash.php',
    'Soli\\Session\\Token'               => __DIR__ . '/Session/Token.php',
    'Soli\\Singleton'                    => __DIR__ . '/Singleton.php',
    'Soli\\View'                         => __DIR__ . '/View.php',
    'Soli\\ViewInterface'                => __DIR__ . '/ViewInterface.php',
    'Soli\\View\\Engine'                 => __DIR__ . '/View/Engine.php',
    'Soli\\View\\EngineInterface'        => __DIR__ . '/View/EngineInterface.php',
    'Soli\\View\\Engine\\Simple'         => __DIR__ . '/View/Engine/Simple.php',
    'Soli\\View\\Engine\\Smarty'         => __DIR__ . '/View/Engine/Smarty.php',
    'Soli\\View\\Engine\\Twig'           => __DIR__ . '/View/Engine/Twig.php',
];
